# Generated by Django 5.2.17 on 2026-08-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='联系邮箱')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网站联系方式',
                'verbose_name_plural': '网站联系方式',
            },
        ),
    ]
