# Generated by Django 5.2.15 on 2026-07-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='公司名称'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tax_no',
            field=models.CharField(blank=True, max_length=80, verbose_name='税号'),
        ),
    ]
