# Generated by Django 5.2.16 on 2026-07-30 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprofile_company_name_userprofile_tax_no"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=150, unique=True, verbose_name="用户名"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="邮箱"),
                ),
                ("company_name", models.CharField(max_length=180, verbose_name="公司名称")),
                ("contact_name", models.CharField(max_length=80, verbose_name="联系人")),
                ("phone", models.CharField(max_length=80, verbose_name="手机/电话")),
                (
                    "purpose",
                    models.TextField(
                        blank=True, help_text="如采购品类、用途等", verbose_name="申请说明"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                ("reject_reason", models.TextField(blank=True, verbose_name="拒绝原因")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_registration_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
            ],
            options={
                "verbose_name": "注册申请",
                "verbose_name_plural": "注册申请",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="accounts_re_status_b9bb8f_idx"
                    ),
                    models.Index(
                        fields=["company_name"], name="accounts_re_company_50bb65_idx"
                    ),
                ],
            },
        ),
    ]
