# Generated by Django 5.2.16 on 2026-08-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_add_registration_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationrequest",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="保存用户设置的登录密码（哈希值），审核通过时回填",
                max_length=256,
                verbose_name="密码哈希",
            ),
        ),
    ]
