# Generated by Django 5.2.15 on 2026-06-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=180, verbose_name='采购企业')),
                ('tax_no', models.CharField(blank=True, max_length=80, verbose_name='税号')),
                ('contact_name', models.CharField(max_length=80, verbose_name='联系人')),
                ('mobile', models.CharField(max_length=80, verbose_name='手机/电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('remark', models.TextField(blank=True, verbose_name='客户备注')),
                ('status', models.CharField(choices=[('active', '正常'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'ordering': ['company_name'],
                'indexes': [models.Index(fields=['company_name'], name='customers_c_company_2610e7_idx'), models.Index(fields=['mobile'], name='customers_c_mobile_e14eb1_idx')],
            },
        ),
    ]
