# Generated by Django 5.2.15 on 2026-06-20 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JstExportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=40, unique=True, verbose_name='批次号')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file', models.FileField(blank=True, upload_to='jst_exports/', verbose_name='导出文件')),
                ('order_count', models.PositiveIntegerField(default=0, verbose_name='订单数')),
                ('status', models.CharField(choices=[('created', '已生成'), ('imported', '导入成功'), ('failed', '导入失败')], default='created', max_length=20, verbose_name='状态')),
                ('exported_at', models.DateTimeField(auto_now_add=True, verbose_name='导出时间')),
                ('error_message', models.TextField(blank=True, verbose_name='异常信息')),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='导出人')),
                ('orders', models.ManyToManyField(blank=True, related_name='export_batches', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '聚水潭导出批次',
                'verbose_name_plural': '聚水潭导出批次',
                'ordering': ['-exported_at'],
                'indexes': [models.Index(fields=['batch_no'], name='integration_batch_n_739149_idx'), models.Index(fields=['status'], name='integration_status_764213_idx')],
            },
        ),
    ]
