# Generated by Django 5.2.15 on 2026-06-20 12:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='分类名称')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='URL 标识')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='产品名称')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='别名/简称')),
                ('style_code', models.CharField(max_length=80, unique=True, verbose_name='款式编码')),
                ('cas_no', models.CharField(blank=True, max_length=80, verbose_name='CAS 号')),
                ('brand', models.CharField(blank=True, max_length=120, verbose_name='品牌')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='产品图片')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('spec_summary', models.TextField(blank=True, verbose_name='关键规格')),
                ('storage_info', models.TextField(blank=True, verbose_name='储存条件')),
                ('safety_info', models.TextField(blank=True, verbose_name='安全说明')),
                ('shipping_info', models.TextField(blank=True, verbose_name='运输说明')),
                ('source_file_name', models.CharField(blank=True, max_length=255, verbose_name='来源文件')),
                ('source_created_by', models.CharField(blank=True, max_length=120, verbose_name='来源创建人')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '上架'), ('archived', '下架')], default='published', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_sku_code', models.CharField(max_length=80, unique=True, verbose_name='内部 SKU 编码')),
                ('jst_sku_id', models.CharField(blank=True, max_length=80, verbose_name='聚水潭商品编码')),
                ('shop_sku_id', models.CharField(blank=True, max_length=80, verbose_name='店铺商品编码')),
                ('source_goods_code', models.CharField(blank=True, max_length=80, verbose_name='来源商品编码')),
                ('source_style_code', models.CharField(blank=True, max_length=80, verbose_name='来源款式编码')),
                ('source_goods_name', models.CharField(blank=True, max_length=255, verbose_name='来源商品名称')),
                ('sku_attribute_text', models.CharField(blank=True, max_length=255, verbose_name='颜色及规格')),
                ('color', models.CharField(blank=True, max_length=120, verbose_name='颜色/型号')),
                ('package_spec', models.CharField(blank=True, max_length=120, verbose_name='包规')),
                ('grade', models.CharField(blank=True, max_length=120, verbose_name='等级')),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='单位')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='单价')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='成本价')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='采购价')),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='市场价')),
                ('moq', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12, verbose_name='起订量')),
                ('order_step', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12, verbose_name='销售步进')),
                ('stock_status', models.CharField(choices=[('in_stock', '有货'), ('confirm', '需确认'), ('presale', '预售'), ('out_of_stock', '缺货'), ('discontinued', '停售')], default='confirm', max_length=20, verbose_name='库存状态')),
                ('inventory_sync_enabled', models.BooleanField(default=True, verbose_name='库存同步')),
                ('source_raw_row', models.JSONField(blank=True, default=dict, verbose_name='原始导入行')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '上架'), ('archived', '下架')], default='published', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='catalog.product', verbose_name='所属产品')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKU',
                'ordering': ['internal_sku_code'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='标题')),
                ('attachment_type', models.CharField(choices=[('sds', 'SDS/MSDS'), ('coa', 'COA'), ('tds', 'TDS'), ('manual', '产品说明书'), ('cert', '资质证书'), ('other', '其他')], default='other', max_length=20, verbose_name='资料类型')),
                ('file', models.FileField(upload_to='attachments/', verbose_name='文件')),
                ('version', models.CharField(blank=True, max_length=60, verbose_name='版本')),
                ('is_public', models.BooleanField(default=True, verbose_name='前台可见')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='catalog.product', verbose_name='产品')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='catalog.sku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': '产品资料',
                'verbose_name_plural': '产品资料',
                'ordering': ['product', 'attachment_type', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='catalog_cat_slug_695af4_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='catalog_cat_parent__e2d7e1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['style_code'], name='catalog_pro_style_c_162502_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='catalog_pro_brand_f6911e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='catalog_pro_status_521020_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='catalog_pro_categor_da0f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['internal_sku_code'], name='catalog_sku_interna_b9ea5d_idx'),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['jst_sku_id'], name='catalog_sku_jst_sku_f30da3_idx'),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['source_style_code'], name='catalog_sku_source__3ad80f_idx'),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['stock_status'], name='catalog_sku_stock_s_4c386b_idx'),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['status'], name='catalog_sku_status_9c3755_idx'),
        ),
    ]
