# Generated by Django 5.2.15 on 2026-06-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_source_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='图片来源 URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='remote_image_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='在线图片 URL'),
        ),
    ]
