# Generated by Django 5.2.15 on 2026-07-03 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image_source_url_product_remote_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='特殊属性'),
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='属性名称')),
                ('code', models.SlugField(max_length=100, verbose_name='属性编码')),
                ('data_type', models.CharField(choices=[('text', '文本'), ('number', '数字'), ('price', '价格'), ('option', '枚举'), ('range', '范围')], default='text', max_length=20, verbose_name='数据类型')),
                ('is_required', models.BooleanField(default=False, verbose_name='必填')),
                ('is_filterable', models.BooleanField(default=True, verbose_name='用于筛选')),
                ('is_list_visible', models.BooleanField(default=False, verbose_name='列表显示')),
                ('is_detail_visible', models.BooleanField(default=True, verbose_name='详情显示')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '分类属性',
                'verbose_name_plural': '分类属性',
                'ordering': ['category', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='catalog_cat_categor_d156aa_idx'), models.Index(fields=['code'], name='catalog_cat_code_32cfda_idx')],
                'unique_together': {('category', 'code')},
            },
        ),
    ]
