# Generated by Django 5.2.16 on 2026-07-31 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_sku_attributes_categoryattribute"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="留空则使用分类名称",
                        max_length=120,
                        verbose_name="显示标题",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="home_categories/", verbose_name="分类图标"
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="留空则跳到该分类的产品列表",
                        max_length=255,
                        verbose_name="跳转链接",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="仅可选择二级分类（其上级为顶级分类）",
                        limit_choices_to={
                            "parent__isnull": False,
                            "parent__parent__isnull": True,
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_entries",
                        to="catalog.category",
                        verbose_name="关联分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "主页分类",
                "verbose_name_plural": "主页分类",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
