# Generated by Django 5.2.16 on 2026-07-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_seed_homecategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.ImageField(
                blank=True, upload_to="category_icons/", verbose_name="分类图标"
            ),
        ),
    ]
