# Generated by Django 5.2.16 on 2026-08-01 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_category_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeScene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80, verbose_name="场景标题")),
                (
                    "subtitle",
                    models.CharField(blank=True, max_length=200, verbose_name="副标题"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=120, unique=True, verbose_name="URL 标识"
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, upload_to="home_scenes/", verbose_name="场景横幅图"
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True, upload_to="home_scenes/icons/", verbose_name="小图标"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "主页场景",
                "verbose_name_plural": "主页场景",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HomeSceneProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_links",
                        to="catalog.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_products",
                        to="catalog.homescene",
                        verbose_name="场景",
                    ),
                ),
            ],
            options={
                "verbose_name": "场景商品",
                "verbose_name_plural": "场景商品",
                "ordering": ["sort_order", "id"],
                "unique_together": {("scene", "product")},
            },
        ),
        migrations.AddField(
            model_name="homescene",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="featured_in_scenes",
                through="catalog.HomeSceneProduct",
                to="catalog.product",
                verbose_name="精选商品",
            ),
        ),
    ]
