# Generated by Django 5.2.16 on 2026-08-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_homescene_homesceneproduct_homescene_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="homescene",
            name="description",
            field=models.TextField(blank=True, verbose_name="场景描述"),
        ),
    ]
