# Generated by Django 5.2.16 on 2026-08-01 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_homescene_description"),
        ("customers", "0002_customer_user_shippingaddress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerSKUPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="协议价"
                    ),
                ),
                (
                    "min_qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="数量 ≥ 该值时生效，留空表示不限制下限",
                        max_digits=12,
                        null=True,
                        verbose_name="起订量",
                    ),
                ),
                (
                    "max_qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="数量 ≤ 该值时生效，留空表示不限制上限",
                        max_digits=12,
                        null=True,
                        verbose_name="封顶量",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(blank=True, null=True, verbose_name="生效开始"),
                ),
                (
                    "valid_to",
                    models.DateField(blank=True, null=True, verbose_name="生效结束"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "remark",
                    models.CharField(blank=True, max_length=255, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sku_prices",
                        to="customers.customer",
                        verbose_name="客户",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_prices",
                        to="catalog.sku",
                        verbose_name="SKU",
                    ),
                ),
            ],
            options={
                "verbose_name": "客户协议价",
                "verbose_name_plural": "客户协议价",
                "ordering": ["customer", "sku", "min_qty"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[("create", "新建"), ("update", "调整"), ("disable", "停用")],
                        max_length=20,
                        verbose_name="变更类型",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="调整前价",
                    ),
                ),
                (
                    "new_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="调整后价",
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=255, verbose_name="原因"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="变更时间"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_histories",
                        to="customers.customer",
                        verbose_name="客户",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "price_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="histories",
                        to="catalog.customerskuprice",
                        verbose_name="协议价记录",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_histories",
                        to="catalog.sku",
                        verbose_name="SKU",
                    ),
                ),
            ],
            options={
                "verbose_name": "协议价变更记录",
                "verbose_name_plural": "协议价变更记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="customerskuprice",
            index=models.Index(
                fields=["customer", "sku"], name="catalog_cus_custome_64357b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerskuprice",
            index=models.Index(
                fields=["sku", "is_active"], name="catalog_cus_sku_id_daa53b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["customer", "sku"], name="catalog_pri_custome_dffb3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["created_at"], name="catalog_pri_created_e3cd4d_idx"
            ),
        ),
    ]
