# Generated by Django 5.2.16 on 2026-08-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_customerskuprice_pricehistory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="capacity",
            field=models.CharField(blank=True, max_length=80, verbose_name="容量"),
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturer_model",
            field=models.CharField(blank=True, max_length=120, verbose_name="制造商型号"),
        ),
        migrations.AddField(
            model_name="sku",
            name="mpq",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="每包数量(MPQ)",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["manufacturer_model"], name="catalog_pro_manufac_c1a06c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["brand", "name", "manufacturer_model"],
                name="catalog_pro_brand_n_d61f24_idx",
            ),
        ),
    ]
