# Generated by Django 5.2.16 on 2026-08-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog",
            "0010_product_capacity_product_manufacturer_model_sku_mpq_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sku",
            name="capacity",
            field=models.CharField(blank=True, max_length=80, verbose_name="容量"),
        ),
    ]
