# Generated by Django 5.2.16 on 2026-08-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_sku_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecategory',
            name='image_display',
            field=models.CharField(choices=[('cover', '覆盖（填充并裁剪）'), ('contain', '包含（完整显示）'), ('fill', '拉伸（填满）'), ('auto', '自适应（保持比例）')], default='cover', help_text='cover: 填充并裁剪（推荐）, contain: 完整显示, fill: 拉伸变形, auto: 浏览器默认', max_length=20, verbose_name='图片显示模式'),
        ),
    ]
