# Generated by Django 5.2.16 on 2026-08-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_add_homecategory_image_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='品牌名称')),
                ('brand_key', models.CharField(blank=True, help_text='用于在 Product.brand 中精确匹配；留空则使用上方名称', max_length=120, verbose_name='品牌 Key')),
                ('logo', models.ImageField(blank=True, upload_to='home_brands/', verbose_name='品牌 Logo')),
                ('description', models.CharField(blank=True, max_length=160, verbose_name='一句话简介')),
                ('link_url', models.CharField(blank=True, help_text='留空则按品牌 Key 过滤产品列表', max_length=255, verbose_name='跳转链接')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '主页品牌',
                'verbose_name_plural': '主页品牌',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='catalog_hom_is_acti_467b59_idx'), models.Index(fields=['brand_key'], name='catalog_hom_brand_k_f161ab_idx')],
            },
        ),
    ]
