# Generated by Django 5.2.16 on 2026-08-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_homebrand'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=120, unique=True, verbose_name='品牌名称')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, help_text='关闭后该品牌不在筛选中显示', verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '品牌排序',
                'verbose_name_plural': '品牌排序',
                'ordering': ['sort_order', 'brand'],
            },
        ),
    ]
