# Generated by Django 5.2.16 on 2026-08-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_add_brand_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': '产品', 'verbose_name_plural': '产品'},
        ),
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='商品目录列表的展示顺序，值小的靠前；相同值时按名称排序', verbose_name='目录排序'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sort_order'], name='catalog_pro_sort_or_8c1a23_idx'),
        ),
    ]
