# Generated by Django 5.2.15 on 2026-06-20 12:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=40, unique=True, verbose_name='网站订单号')),
                ('status', models.CharField(choices=[('draft', '待提交'), ('pending_company_confirm', '待公司确认'), ('pending_customer_confirm', '待客户确认'), ('pending_jst_export', '待导入聚水潭'), ('exported', '已导出聚水潭'), ('jst_error', '聚水潭处理异常'), ('accepted', '已受理'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending_company_confirm', max_length=40, verbose_name='状态')),
                ('receiver_name', models.CharField(max_length=80, verbose_name='收件人')),
                ('receiver_mobile', models.CharField(max_length=80, verbose_name='手机/电话')),
                ('receiver_state', models.CharField(blank=True, max_length=80, verbose_name='省')),
                ('receiver_city', models.CharField(blank=True, max_length=80, verbose_name='市')),
                ('receiver_district', models.CharField(blank=True, max_length=80, verbose_name='区')),
                ('receiver_address', models.CharField(max_length=255, verbose_name='详细地址')),
                ('invoice_info', models.TextField(blank=True, verbose_name='开票信息')),
                ('buyer_message', models.TextField(blank=True, verbose_name='买家留言')),
                ('internal_remark', models.TextField(blank=True, verbose_name='内部备注')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='订单总额')),
                ('freight', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='运费')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='期望交期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('exported_at', models.DateTimeField(blank=True, null=True, verbose_name='最近导出时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_product_name', models.CharField(max_length=255, verbose_name='产品名称快照')),
                ('snapshot_sku_code', models.CharField(max_length=80, verbose_name='SKU 编码快照')),
                ('snapshot_jst_sku_id', models.CharField(blank=True, max_length=80, verbose_name='聚水潭编码快照')),
                ('snapshot_shop_sku_id', models.CharField(blank=True, max_length=80, verbose_name='店铺编码快照')),
                ('properties_value', models.CharField(blank=True, max_length=255, verbose_name='商品属性快照')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='单价')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='数量')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='明细金额')),
                ('confirmed_stock_status', models.CharField(blank=True, max_length=80, verbose_name='库存确认')),
                ('expected_ship_date', models.DateField(blank=True, null=True, verbose_name='预计发货日期')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='明细备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='订单')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='产品')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.sku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_no'], name='orders_orde_order_n_7a9a09_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['snapshot_sku_code'], name='orders_orde_snapsho_002618_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['snapshot_jst_sku_id'], name='orders_orde_snapsho_35eb1a_idx'),
        ),
    ]
