# Generated by Django 5.2.16 on 2026-08-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="price_source",
            field=models.CharField(
                blank=True,
                help_text="sku_default=默认标价 / customer_price=客户协议价",
                max_length=20,
                verbose_name="价格来源",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="snapshot_customer_price_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="协议价记录 ID"
            ),
        ),
    ]
